# Generated by Django 6.1 on 2026-09-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='aprovado',
            field=models.BooleanField(default=True, help_text='Indica se o entregador/usuário foi aprovado para utilizar o sistema.', verbose_name='Cadastro Aprovado'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('entregador', 'Entregador'), ('admin', 'Administrador')], default='cliente', max_length=20, verbose_name='Perfil do Usuário'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone / WhatsApp'),
        ),
    ]
