name: Django CI - Renk Gás

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar o código do repositório
      uses: actions/checkout@v4

    - name: Configurar versão do Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Instalar Dependências
      run: |
        python -m pip install --upgrade pip
        pip install django psycopg2-binary django-unfold

    - name: Executar Testes Automatizados (TDD)
      run: |
        python manage.py test