# Generated by Django 6.1 on 2026-09-02 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bairro', models.CharField(choices=[('Jardim Campos', 'Jardim Campos'), ('Jardim Nazaré', 'Jardim Nazaré'), ('Jardim Robru', 'Jardim Robru'), ('Vila Lourdes', 'Vila Lourdes')], max_length=50, verbose_name='Bairro de Entrega')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço Completo')),
                ('quantidade_gas', models.PositiveIntegerField(default=1, verbose_name='Quantidade de Botijões')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ROTA', 'Em Rota de Entrega'), ('ENTREGUE', 'Entregue'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20, verbose_name='Status do Pedido')),
                ('observacao', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data do Pedido')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_cliente', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('entregador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_entregador', to=settings.AUTH_USER_MODEL, verbose_name='Entregador Designado')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
