# Generated by Django 6.1 on 2026-09-03 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bairro',
            options={},
        ),
        migrations.AddField(
            model_name='pedido',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bairro',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bairro',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='bairro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='deliveries.bairro'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='endereco_entrega',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='entregador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_entregador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='forma_pagamento',
            field=models.CharField(choices=[('PIX', 'PIX'), ('CARTAO', 'Cartão na Entrega'), ('DINHEIRO', 'Dinheiro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
